version: 2.1

###############################################################################
# Variables
###############################################################################

postgres: &postgres
  - image: cimg/postgres:12.8
    environment:
      POSTGRES_USER: debug
      POSTGRES_PASSWORD: debug
      POSTGRES_DB: greatcms

postgres_url: &postgres_url
  DATABASE_URL: postgresql://debug:debug@localhost/greatcms

python: &python
  image: cimg/python:3.9.13

python_node_browsers: &python_node_browsers
  image: cimg/python:3.9.13-browsers

setup_db: &setup_db
  run:
    name: Database Setup
    command: |
      . venv/bin/activate
      make database
      make ARGUMENTS=migrate manage
      make ARGUMENTS=bootstrap_great manage

###############################################################################
# Steps
###############################################################################

create_virtualenv_and_install_dependencies:
  &create_virtualenv_and_install_dependencies
  run:
    name: Create virtualenv and install dependencies
    command: |
      python3 -m venv venv
      . venv/bin/activate
      pip install --upgrade pip
      make install_requirements

setup_secrets: &setup_secrets
  run:
    name: Setup Secrets
    command: |
      . venv/bin/activate
      make secrets

install_libcairo2: &install_libcairo2
  run:
    name: Install libcairo2-dev
    command: |
      sudo apt-get update
      sudo apt-get install libcairo2-dev

install_postgresql_client: &install_postgresql_client
  run:
    name: Install PostgreSQL Client
    command: |
      sudo apt-get update
      sudo apt-get install postgresql-client

###############################################################################
# Jobs
###############################################################################

jobs:
  flake8:
    docker:
      - <<: *python
    steps:
      - checkout
      - *install_libcairo2
      - run:
          name: Run flake8
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --quiet -r requirements_dev.txt
            flake8

  black:
    docker:
      - <<: *python
    steps:
      - checkout
      - run:
          name: Run Black in check mode
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install black
            black ./ --check

  test_behavioural:
    docker:
      - <<: *python
    steps:
      - checkout
      - run:
          name: Run behave
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install behave
            make behavioural_tests

  test_javascript:
    docker:
      - *python_node_browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install node modules
          command: npm ci
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - 'node_modules'
      - run:
          name: Run Javascript tests
          command: npm test -- --maxWorkers=1

  test_load:
    working_directory: ~/greatcms
    docker:
      - <<: *python
      - <<: *postgres
    environment:
      NUM_USERS: 20
      HATCH_RATE: 3
      RUN_TIME: 30s
      <<: *postgres_url
    steps:
      - checkout
      - *install_postgresql_client
      - *install_libcairo2
      - *create_virtualenv_and_install_dependencies
      - *setup_secrets
      - *setup_db
      - run:
          name: Run tests
          command: |
            python3 -m venv venv
            . venv/bin/activate
            mkdir results
            make load_tests
      - store_artifacts:
          path: ./results/
          destination: locust_results

  test_unit:
    working_directory: ~/greatcms
    docker:
      - <<: *python_node_browsers
      - <<: *postgres
    environment: *postgres_url
    steps:
      - checkout
      - *install_postgresql_client
      - restore_cache:
          key: v1-deps-{{ checksum "requirements_dev.txt" }}
      - *create_virtualenv_and_install_dependencies
      - *setup_secrets
      - save_cache:
          key: v1-deps-{{ checksum "requirements_dev.txt" }}
          paths:
            - 'venv'
      - run:
          name: Run Unit tests
          command: |
            . venv/bin/activate
            make pytest_codecov -- --codecov-token=${CODECOV_TOKEN}
      - store_test_results:
          path: ./results/

###############################################################################
# Workflows
###############################################################################

workflows:
  version: 2
  test_and_checks:
    jobs:
      - test_behavioural
      - test_javascript
      - test_load
      - test_unit
      - flake8
      - black
