version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.2

###############################################################################
# Variables
###############################################################################

python: &python
  image: cimg/python:3.9.13

python_node_browsers: &python_node_browsers
  image: cimg/python:3.9.13-browsers

###############################################################################
# Steps
###############################################################################

create_virtualenv_and_install_dependencies:
  &create_virtualenv_and_install_dependencies
  run:
    name: Create virtualenv and install dependencies
    command: |
      python3 -m venv venv
      . venv/bin/activate
      pip install --upgrade pip
      make install_requirements

setup_secrets: &setup_secrets
  run:
    name: Setup Secrets
    command: |
      . venv/bin/activate
      make secrets

install_libcairo2: &install_libcairo2
  run:
    name: Install libcairo2-dev
    command: |
      sudo apt-get update
      sudo apt-get install libcairo2-dev


###############################################################################
# Jobs
###############################################################################

jobs:
  flake8:
    docker:
      - <<: *python
    steps:
      - checkout
      - *install_libcairo2
      - run:
          name: Run flake8
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --quiet -r requirements_dev.txt
            flake8

  black:
    docker:
      - <<: *python
    steps:
      - checkout
      - run:
          name: Run Black in check mode
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install black
            black ./ --check

###############################################################################
# Workflows
###############################################################################

workflows:
  version: 2
  test_and_checks:
    jobs:
      - flake8
      - black
